from __future__ import annotations

from pathlib import Path

from kronweave.io.metadata import build_metadata, write_metadata
from kronweave.io.readme_writer import write_bundle_readme
from kronweave.io.tensorsuite import write_tns, write_tnsb_from_tns
from kronweave.postprocess.values import infer_value_domain
from kronweave.seed.cpd import generate_cp_seed


def write_cp_seed_bundle(
    bundle_dir: str | Path,
    *,
    name: str,
    config: dict,
    config_path: str | None = None,
) -> dict:
    seed_cfg = config["seed"]
    cpd_cfg = seed_cfg.get("cpd", seed_cfg)
    tensor_cfg = config.get("tensor", {})
    generator_cfg = config.get("generator", {})
    output_cfg = config.get("output", {})
    index_base = int(tensor_cfg.get("index_base", 0))
    coords, values = generate_cp_seed(
        sizes=cpd_cfg["sizes"],
        rank=int(cpd_cfg["rank"]),
        alpha=cpd_cfg["alpha"],
        noise=float(cpd_cfg.get("noise", 0.0)),
        random_seed=generator_cfg.get("random_seed"),
        lambda_controller=cpd_cfg.get("lambda_controller", "softmax"),
    )
    bundle_dir = Path(bundle_dir)
    bundle_dir.mkdir(parents=True, exist_ok=True)
    tns_path = bundle_dir / f"{name}.tns"
    tnsb_path = bundle_dir / f"{name}.tnsb"
    metadata_path = bundle_dir / f"{name}_metadata.json"
    write_tns(tns_path, name, cpd_cfg["sizes"], coords, values, index_base=index_base)
    if output_cfg.get("write_tnsb", True):
        write_tnsb_from_tns(tns_path, tnsb_path)
    metadata = build_metadata(
        name=name,
        dims=cpd_cfg["sizes"],
        nnz=len(values),
        index_base=index_base,
        value_domain=infer_value_domain({"mode": "uniform", "low": 0.0, "high": 1.0}),
        duplicate_policy="keep",
    )
    write_metadata(metadata_path, metadata)
    write_bundle_readme(
        bundle_dir / "README.md",
        name,
        metadata,
        config,
        config_path=config_path,
        config_snapshot_path="../config.yaml",
        generation_info={
            "role": "cp_seed",
            "meta_seed": "This bundle is the CP seed generated by `seed/cpd.py` and consumed by fastSKG.",
        },
    )
    return {
        "name": name,
        "bundle_dir": bundle_dir,
        "tns": tns_path,
        "tnsb": tnsb_path,
        "metadata": metadata_path,
        "coords": coords,
        "values": values,
    }


# Backward-compatible alias for older callers.
write_cp_meta_seed_bundle = write_cp_seed_bundle


def write_cp_seed_from_meta_bundle(
    bundle_dir: str | Path,
    *,
    name: str,
    source_tns: str | Path,
    config: dict,
    config_path: str | None = None,
) -> dict:
    """Backward-compatible CP seed writer.

    Older configs passed a ``source_tns`` meta-seed path here. The current CPD
    path intentionally does not read that tensor; it mirrors
    ``seed_generator_cpd.py`` and generates the full CP seed directly from
    ``seed.cpd`` parameters in KronWeave TensorSuite format.
    """
    _ = source_tns
    seed_cfg = config["seed"]
    tensor_cfg = config.get("tensor", {})
    output_cfg = config.get("output", {})
    index_base = int(tensor_cfg.get("index_base", 0))
    cpd_cfg = seed_cfg["cpd"]
    coords, values = generate_cp_seed(
        sizes=cpd_cfg["sizes"],
        rank=int(cpd_cfg["rank"]),
        alpha=cpd_cfg["alpha"],
        noise=float(cpd_cfg.get("noise", 0.0)),
        random_seed=config.get("generator", {}).get("random_seed"),
        lambda_controller=cpd_cfg.get("lambda_controller", "softmax"),
    )
    cp_seed_sizes = [int(x) for x in cpd_cfg["sizes"]]
    bundle_dir = Path(bundle_dir)
    bundle_dir.mkdir(parents=True, exist_ok=True)
    tns_path = bundle_dir / f"{name}.tns"
    tnsb_path = bundle_dir / f"{name}.tnsb"
    metadata_path = bundle_dir / f"{name}_metadata.json"
    write_tns(tns_path, name, cp_seed_sizes, coords, values, index_base=index_base)
    if output_cfg.get("write_tnsb", True):
        write_tnsb_from_tns(tns_path, tnsb_path)
    metadata = build_metadata(
        name=name,
        dims=cp_seed_sizes,
        nnz=len(values),
        index_base=index_base,
        value_domain="nonnegative",
        duplicate_policy="keep",
    )
    write_metadata(metadata_path, metadata)
    write_bundle_readme(
        bundle_dir / "README.md",
        name,
        metadata,
        config,
        config_path=config_path,
        config_snapshot_path="../config.yaml",
        generation_info={
            "role": "cp_seed",
            "meta_seed": (
                f"Legacy source_tns argument was ignored. CPD parameters generated this CP seed directly "
                f"with sizes={cp_seed_sizes}, rank={cpd_cfg['rank']}, alpha={cpd_cfg['alpha']}, "
                f"noise={cpd_cfg.get('noise', 0.0)}. This CP seed is the fastSKG input."
            ),
        },
    )
    return {
        "name": name,
        "bundle_dir": bundle_dir,
        "tns": tns_path,
        "tnsb": tnsb_path,
        "metadata": metadata_path,
        "coords": coords,
        "values": values,
        "cp_seed_sizes": cp_seed_sizes,
    }


# Backward-compatible alias for callers that have not yet been updated.
write_kp_seed_from_meta_bundle = write_cp_seed_from_meta_bundle
